name: Build and test images
on:
  push:
    branches-ignore:
      - develop
      - main
      - 'release/**'
jobs:
  generate_matrix:
    runs-on: ubuntu-22.04
    container:
      image: docker://alpine/git:v2.36.3
    outputs:
      matrix: ${{ steps.read.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: read
        run: .ci/extract_github_action_matrix_as.sh matrix
  build_and_test:
    needs: generate_matrix
    runs-on: ubuntu-22.04
    container:
      image: docker://docker:stable-git
      options: --name=runner
    strategy:
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and test
        run: ./ci_cd.sh --build --test --android-api ${{ matrix.android_api.api }} --build-tools ${{ matrix.android_api.build_tools }} ${{ matrix.android_ndk }} {{ matrix.gcloud }}
