name: Test action
on:
  push:
    branches-ignore:
      - develop
      - main
      - 'release/**'
jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    container:
      image: docker://docker:stable-git
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test action
        uses: ./
        id: docker-android-action
        with:
          exec: sh action/test_action.sh
